### ISSUE TITLE
Cannot run this app

### ISSUE THREAD

**Issue by jashshah** [muschellij2/Shiny_Health_Data#1]
Hi,
I have cloned your repository and followed the instructions of your README file but I cannot run the file. All it says is 

`Listening on http:// xxxx
NULL`

Can you please help?

**Comment by muschellij2** [comment]
I just tried it and it seemed to work for me.

I am not currently maintaining this application.  Please try to upgrade your shiny and other packages and rerun but will not have time at the moment to debug.

**Comment by jashshah** [comment]
Posting for other people who cannot run this app: just uncomment all the coded that's commented out from server.R except for the one on line 42.
